customhost = "employee.c0pukpb10sbq.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "BAIT3273"
customdb = "employee"
custombucket = "jonchewchunwai-employee"
customregion = "us-east-1"
